### ISSUE TITLE
feat: EventForm for creating new events

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [Infinite-Sum-Games/ace-admin#23]
# Requirements
- [ ] A React-Form for creating new events
- [ ] Image Uploader component using `UploadThing` for Event-Posters
- [ ] Events should automatically move to draft if not published
- [ ] The entire component can be a `Sheet` from ShadCN/UI which opens on the right and occupies half the width of the screen.

Input fields for the form are as follows:
1. Title
2. Description (Markdown Editor)
3. Date & Time Picker (Start and End)
4. Tags (~3 maximum)
5. EventPoster (Portrait - 10MB limit)
6. Guests (should be able to add more than 1 guest)
7. Publishing status - (Draft / Publish)
8. Payment status - (Paid / Unpaid)
9. Fee (if Paid)
10. Venue (mention if Online)
11. Seats (exact-count / unlimited)

All the requirements should be satisfied before raising a PR. Please ask for any clarifying questions in the comment section of this issue.

**Comment by vijay-sb** [comment]
EventForm Created and merged successfully.
